import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useS3Upload } from 'next-s3-upload';
import { useState } from 'react';

export default function Home() {
	let [imageUrl, setImageUrl] = useState();
	let { uploadToS3, openFileDialog, files } = useS3Upload();

	let handleFileChange = async (event) => {
		let file = event.target.files[0];
		let { url } = await uploadToS3(file);

		console.log(files);
		console.log(url);
		setImageUrl(url);
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1>Next JS S3 Upload</h1>
				<br />
				<input type="file" onChange={handleFileChange} />
				<br />
				<button onClick={openFileDialog}>Upload file</button>
				<br />
				{imageUrl && (
					<Image src={imageUrl} alt="productImg" width={500} height={500} />
				)}
			</main>
		</div>
	);
}
